language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  # get miniconda
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $PWD/anaconda
  - anaconda/bin/conda update --yes --quiet conda
  # install and extract ffmpg static binary to current directory
  - anaconda/bin/conda install --yes -c menpo ffmpeg=3.1.3
  - cp anaconda/bin/ffmpeg .
  - ./ffmpeg -version
  - export PATH=".:$PATH"

  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: esc
  server: https://upload.pypi.org/legacy/
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "KCpujl0BktlkSBzO+3TzbZI/c8W7jdPtZx/9Nnz2TbXqgJjKhQYoHHTZfXV0Ubt05s669ef+FlXu5UembEQ23Nc3oMtd0omCulLBmDVMHdnu7tfjSw1gVO2cgOhSKgcYBT7O31PiWMTOKcpLMlDRIpVRQfV8bs6elyBRZGGPiIL8MC/KdPwpyeqIje26yFX27Sz0PLrDdnj9gck8yS7LcdMXE7UmiubN8csesE2OXvr5jfiTvZsd1X7esqmhCiSTdmhEWoyXAI890wF/C8pN5HmxtwkGAf4aGnMpR8Aa3knbZbq1H/NjwHAZH0+V9Q9kFirZO8HNySH1ZvQXwP+k0/raooWXVK/VMgPs2iIqanyQfSbLcJ+asCQoh2G/oHIRvp233u3JVyzSzlnifFbiqV1CRAQswkl8FObGonmBnXIZtc9KJ9Yzx57deyBepRDYfIN0DneKPJ410Min3QNHDxOx5aKYUvWS78m1tgX1dBMM3bl+3pFbBtLSIc30nSJd8nNCJbaaXNzD9KmYpI2iTkurz4OA7xtufz6Oe//U3qGLBvC3QFL/aOCiYbbmGao7Yo6Wx878eTQ9azPMaCd8NuElaIv4mxa/73jeSj3dZhzKvVTatxzBkiFYrOhhJtvxx1mveiqkBYR8xx2P0fbaZ7/tReEJJJhbTi60YvhtboI="
  on:
    repo: TwentyBN/GulpIO
    python: '3.6'
    branch: master
